import { storage } from './storage';
import type { InsertProduct } from '@shared/schema';

const sampleProducts: InsertProduct[] = [
  {
    name: "NFT Flat Bed Kit (Small)",
    description: "Perfect starter kit for hydroponic beginners. Compact design suitable for home use with easy setup and maintenance.",
    price: "15000",
    category: "Home Grower Kit",
    images: ["/api/images/nft-small.jpg"],
    unit: "per unit",
    specifications: ["ABS coated pipe", "Double layer UPVC channels"],
    planterCount: 36,
    dimensions: "4.9 x 2.9 x 2.8 ft",
    cultivableCrops: "Leafy greens",
    structureMaterial: "ABS coated pipe",
    inStock: 8,
  },
  {
    name: "NFT Flat Bed Kit (Medium)",
    description: "Ideal for medium-scale home farming. Higher capacity with professional-grade components for consistent yields.",
    price: "25000",
    category: "Home Grower Kit",
    images: ["/api/images/nft-medium.jpg"],
    unit: "per unit",
    specifications: ["ABS coated pipe", "Double layer UPVC channels"],
    planterCount: 114,
    dimensions: "9.8 x 4.2 x 2.7 ft",
    cultivableCrops: "Leafy greens",
    structureMaterial: "ABS coated pipe",
    inStock: 5,
  },
  {
    name: "NFT Flat Bed Kit (Commercial)",
    description: "Large-scale commercial hydroponic system. Built for high-volume production with industrial-grade materials.",
    price: "65000",
    category: "Commercial Kit",
    images: ["/api/images/nft-commercial.jpg"],
    unit: "per unit",
    specifications: ["ABS coated pipe", "Double layer UPVC channels"],
    planterCount: 300,
    dimensions: "19.6 x 5.9 x 2.7 ft",
    cultivableCrops: "Leafy greens",
    structureMaterial: "ABS coated pipe",
    inStock: 3,
  },
  {
    name: "Dutch Bucket Kit (Medium)",
    description: "Excellent for growing vine crops and vegetables. Modular design allows for easy expansion and maintenance.",
    price: "18000",
    category: "Home Grower Kit",
    images: ["/api/images/dutch-bucket.jpg"],
    unit: "per unit",
    specifications: ["MS tube structure", "Modular bucket system"],
    planterCount: 10,
    dimensions: "4 x 2 x 0.8 ft",
    cultivableCrops: "Vegetables, vine crops",
    structureMaterial: "MS tube",
    inStock: 6,
  },
  {
    name: "NFT A-Frame Kit (Medium)",
    description: "Space-efficient vertical growing system. Maximizes growing capacity in minimal footprint.",
    price: "22000",
    category: "Home Grower Kit",
    images: ["/api/images/nft-aframe.jpg"],
    unit: "per unit",
    specifications: ["ABS coated pipe", "A-frame design"],
    planterCount: 36,
    dimensions: "4.9 x 2.9 x 2.8 ft",
    cultivableCrops: "Leafy greens",
    structureMaterial: "ABS coated pipe",
    inStock: 4,
  },
  {
    name: "NFT A-Frame Kit (Commercial)",
    description: "High-capacity vertical farming solution. Perfect for commercial operations requiring maximum yield per square foot.",
    price: "85000",
    category: "Commercial Kit",
    images: ["/api/images/nft-aframe-commercial.jpg"],
    unit: "per unit",
    specifications: ["MS tube structure", "High-capacity design"],
    planterCount: 300,
    dimensions: "22.6 x 4.4 x 5.2 ft",
    cultivableCrops: "Leafy greens",
    structureMaterial: "MS tube",
    inStock: 2,
  },
  {
    name: "Cocopeat & Husk Bags (5kg)",
    description: "Premium quality growing medium made from coconut coir. Low EC, perfect pH balance for hydroponic systems.",
    price: "800",
    category: "Coir Products",
    images: ["/api/images/cocopeat-bags.jpg"],
    unit: "per bag",
    specifications: ["EC ≤ 0.2", "pH 5.8–6.5", "Moisture: Air 30:70"],
    planterCount: null,
    dimensions: "5kg bag",
    cultivableCrops: "All hydroponic crops",
    structureMaterial: "100% Natural coir",
    inStock: 25,
  },
  {
    name: "Perlite Growing Medium",
    description: "Lightweight volcanic glass growing medium. Excellent drainage and aeration properties for root health.",
    price: "1200",
    category: "Grow Media",
    images: ["/api/images/perlite.jpg"],
    unit: "per bag",
    specifications: ["0.5–4 mm", "Density: 120–150 Kg/m³"],
    planterCount: null,
    dimensions: "10kg bag",
    cultivableCrops: "All hydroponic crops",
    structureMaterial: "Volcanic glass",
    inStock: 15,
  },
  {
    name: "Submersible Pump JQP 2500",
    description: "Reliable water pump for hydroponic systems. Quiet operation with excellent flow rate and durability.",
    price: "2500",
    category: "Accessories",
    images: ["/api/images/pump.jpg"],
    unit: "per piece",
    specifications: ["35W power", "2500L/hr flow rate"],
    planterCount: null,
    dimensions: "Compact design",
    cultivableCrops: "System component",
    structureMaterial: "High-grade plastic",
    inStock: 12,
  },
  {
    name: "pH Meter - HM Digital pH-80",
    description: "Digital pH meter for accurate monitoring of nutrient solution. Essential for maintaining optimal growing conditions.",
    price: "3500",
    category: "Accessories",
    images: ["/api/images/ph-meter.jpg"],
    unit: "per piece",
    specifications: ["pH Range: 0–14", "Temperature compensation", "Digital calibration"],
    planterCount: null,
    dimensions: "Portable handheld",
    cultivableCrops: "System component",
    structureMaterial: "Waterproof plastic",
    inStock: 20,
  },
  // Leafy Greens
  {
    name: "Fresh Lettuce (Green)",
    description: "Crisp, pesticide-free green lettuce grown hydroponically. Perfect for salads and sandwiches.",
    price: "40",
    category: "Leafy Greens",
    images: ["/api/images/lettuce-green.jpg"],
    unit: "per 100g",
    specifications: ["Hydroponically grown", "Pesticide-free", "Freshly harvested"],
    inStock: 50,
  },
  {
    name: "Fresh Lettuce (Red)",
    description: "Vibrant red lettuce with a mild, sweet flavor. Rich in antioxidants and perfect for colorful salads.",
    price: "45",
    category: "Leafy Greens",
    images: ["/api/images/lettuce-red.jpg"],
    unit: "per 100g",
    specifications: ["Hydroponically grown", "Pesticide-free", "High in antioxidants"],
    inStock: 45,
  },
  {
    name: "Baby Spinach",
    description: "Tender baby spinach leaves packed with nutrients. Ideal for salads, smoothies, and cooking.",
    price: "50",
    category: "Leafy Greens",
    images: ["/api/images/spinach.jpg"],
    unit: "per 100g",
    specifications: ["Hydroponically grown", "Pesticide-free", "High in iron & vitamins"],
    inStock: 60,
  },
  {
    name: "Kale (Curly)",
    description: "Nutrient-dense curly kale with a slightly peppery flavor. Superfood for salads and smoothies.",
    price: "55",
    category: "Leafy Greens",
    images: ["/api/images/kale.jpg"],
    unit: "per 100g",
    specifications: ["Hydroponically grown", "Pesticide-free", "Rich in vitamins K, A, C"],
    inStock: 40,
  },
  {
    name: "Arugula (Rocket)",
    description: "Peppery arugula leaves with a distinctive nutty flavor. Perfect for gourmet salads and pizzas.",
    price: "60",
    category: "Leafy Greens",
    images: ["/api/images/arugula.jpg"],
    unit: "per 100g",
    specifications: ["Hydroponically grown", "Pesticide-free", "Distinctive peppery taste"],
    inStock: 35,
  },
  {
    name: "Bok Choy",
    description: "Mild, crunchy Asian green vegetable. Excellent for stir-fries and soups.",
    price: "45",
    category: "Leafy Greens",
    images: ["/api/images/bokchoy.jpg"],
    unit: "per piece",
    specifications: ["Hydroponically grown", "Pesticide-free", "Rich in vitamins A & C"],
    inStock: 30,
  },
  {
    name: "Swiss Chard (Rainbow)",
    description: "Colorful rainbow chard with vibrant stems. Nutritious and visually stunning.",
    price: "50",
    category: "Leafy Greens",
    images: ["/api/images/chard.jpg"],
    unit: "per bunch",
    specifications: ["Hydroponically grown", "Pesticide-free", "Colorful & nutritious"],
    inStock: 25,
  },
  {
    name: "Romaine Lettuce",
    description: "Crisp romaine lettuce heads with a sweet, mild flavor. Classic Caesar salad ingredient.",
    price: "40",
    category: "Leafy Greens",
    images: ["/api/images/romaine.jpg"],
    unit: "per piece",
    specifications: ["Hydroponically grown", "Pesticide-free", "Crisp texture"],
    inStock: 40,
  },
  // Herbs
  {
    name: "Fresh Basil",
    description: "Aromatic sweet basil with intense flavor. Essential for Italian cuisine and pesto.",
    price: "30",
    category: "Herbs",
    images: ["/api/images/basil.jpg"],
    unit: "per 50g",
    specifications: ["Hydroponically grown", "Pesticide-free", "Highly aromatic"],
    inStock: 80,
  },
  {
    name: "Fresh Mint",
    description: "Refreshing mint leaves perfect for drinks, desserts, and Middle Eastern dishes.",
    price: "25",
    category: "Herbs",
    images: ["/api/images/mint.jpg"],
    unit: "per 50g",
    specifications: ["Hydroponically grown", "Pesticide-free", "Cooling & refreshing"],
    inStock: 70,
  },
  {
    name: "Fresh Cilantro (Coriander Leaves)",
    description: "Fragrant cilantro leaves essential for Indian, Mexican, and Asian cuisines.",
    price: "20",
    category: "Herbs",
    images: ["/api/images/cilantro.jpg"],
    unit: "per bunch",
    specifications: ["Hydroponically grown", "Pesticide-free", "Highly fragrant"],
    inStock: 90,
  },
  {
    name: "Fresh Parsley",
    description: "Versatile flat-leaf parsley with fresh, slightly peppery flavor. Perfect garnish and ingredient.",
    price: "25",
    category: "Herbs",
    images: ["/api/images/parsley.jpg"],
    unit: "per bunch",
    specifications: ["Hydroponically grown", "Pesticide-free", "Rich in vitamin K"],
    inStock: 75,
  },
  {
    name: "Fresh Thyme",
    description: "Earthy thyme with a subtle minty aroma. Perfect for roasts, stews, and Mediterranean dishes.",
    price: "35",
    category: "Herbs",
    images: ["/api/images/thyme.jpg"],
    unit: "per 50g",
    specifications: ["Hydroponically grown", "Pesticide-free", "Earthy & aromatic"],
    inStock: 50,
  },
  {
    name: "Fresh Rosemary",
    description: "Woody, pine-scented rosemary. Ideal for roasted meats, potatoes, and breads.",
    price: "40",
    category: "Herbs",
    images: ["/api/images/rosemary.jpg"],
    unit: "per 50g",
    specifications: ["Hydroponically grown", "Pesticide-free", "Pine-like aroma"],
    inStock: 45,
  },
  // Exotic Vegetables
  {
    name: "Cherry Tomatoes",
    description: "Sweet, bite-sized cherry tomatoes bursting with flavor. Perfect for salads and snacking.",
    price: "80",
    category: "Exotic Vegetables",
    images: ["/api/images/cherry-tomatoes.jpg"],
    unit: "per 250g",
    specifications: ["Hydroponically grown", "Pesticide-free", "Sweet & juicy"],
    inStock: 55,
  },
  {
    name: "Bell Peppers (Mixed Colors)",
    description: "Colorful bell peppers in red, yellow, and orange. Crisp, sweet, and vitamin-rich.",
    price: "120",
    category: "Exotic Vegetables",
    images: ["/api/images/bell-peppers.jpg"],
    unit: "per piece",
    specifications: ["Hydroponically grown", "Pesticide-free", "High in vitamin C"],
    inStock: 40,
  },
  {
    name: "English Cucumber",
    description: "Long, seedless English cucumber with mild flavor and crisp texture.",
    price: "60",
    category: "Exotic Vegetables",
    images: ["/api/images/cucumber.jpg"],
    unit: "per piece",
    specifications: ["Hydroponically grown", "Pesticide-free", "Seedless & crisp"],
    inStock: 45,
  },
  {
    name: "Strawberries (Hydroponic)",
    description: "Sweet, juicy strawberries grown in controlled hydroponic environment. Year-round availability.",
    price: "200",
    category: "Exotic Vegetables",
    images: ["/api/images/strawberries.jpg"],
    unit: "per 250g",
    specifications: ["Hydroponically grown", "Pesticide-free", "Sweet & aromatic"],
    inStock: 30,
  },
  {
    name: "Microgreens Mix",
    description: "Nutrient-dense microgreens mix including radish, broccoli, and mustard. Superfood garnish.",
    price: "150",
    category: "Exotic Vegetables",
    images: ["/api/images/microgreens.jpg"],
    unit: "per 100g",
    specifications: ["Hydroponically grown", "Pesticide-free", "Nutrient-dense superfood"],
    inStock: 25,
  },
  {
    name: "Zucchini (Green)",
    description: "Fresh, tender zucchini perfect for grilling, sautéing, or spiralizing into healthy noodles.",
    price: "70",
    category: "Exotic Vegetables",
    images: ["/api/images/zucchini.jpg"],
    unit: "per piece",
    specifications: ["Hydroponically grown", "Pesticide-free", "Low calorie"],
    inStock: 35,
  },
  {
    name: "Eggplant (Purple)",
    description: "Glossy purple eggplant with creamy flesh. Perfect for grilling, roasting, or curry dishes.",
    price: "90",
    category: "Exotic Vegetables",
    images: ["/api/images/eggplant.jpg"],
    unit: "per piece",
    specifications: ["Hydroponically grown", "Pesticide-free", "Rich in fiber"],
    inStock: 30,
  },
];

async function seedProducts() {
  try {
    console.log('🔍 Checking existing products...');
    const existingProducts = await storage.getProducts();
    const existingProductNames = new Set(existingProducts.map(p => p.name));
    
    let newProductsCount = 0;
    let skippedProductsCount = 0;
    
    for (const product of sampleProducts) {
      if (!existingProductNames.has(product.name)) {
        const created = await storage.createProduct(product);
        console.log(`✅ Created product: ${created.name}`);
        newProductsCount++;
      } else {
        skippedProductsCount++;
      }
    }
    
    console.log(`🎉 Database seeding complete!`);
    console.log(`   - New products added: ${newProductsCount}`);
    console.log(`   - Products skipped (already exist): ${skippedProductsCount}`);
    console.log(`   - Total products in database: ${existingProducts.length + newProductsCount}`);
  } catch (error) {
    console.error('❌ Error seeding products:', error);
    process.exit(1);
  }
}

// Export the function for use in startup
export { seedProducts };