import { useMemo, useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useAuthenticatedFetch } from "@/context/AuthContext";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Ticket, RotateCcw, Tag, Gift, Users, Shield, ClipboardList, ShoppingBag, Truck } from "lucide-react";

export default function AdminCommerceFeatures() {
  const authenticatedFetch = useAuthenticatedFetch();
  const jsonFetch = async (url: string, options?: RequestInit) => {
    const response = await authenticatedFetch(url, options);
    if (!response.ok) throw new Error((await response.text()) || "Request failed");
    return response.json();
  };
  const qc = useQueryClient();
  const [coupon, setCoupon] = useState({ code: "", discountType: "percentage", discountValue: "10", minimumOrderAmount: "0", maximumDiscountAmount: "", usageLimit: "", perCustomerLimit: "1", firstOrderOnly: false });
  const [gift, setGift] = useState({ code: "", initialAmount: "500", recipientEmail: "", message: "" });
  const [shippingRule, setShippingRule] = useState({ name: "", country: "India", state: "", shippingCharge: "99", freeShippingThreshold: "" , priority: "100" });
  const [carrier, setCarrier] = useState({ name: "", trackingUrlTemplate: "" });
  const [permission, setPermission] = useState({ userId: "", permissions: "orders,products,inventory,customers,support,coupons,returns,settings" });

  const coupons = useQuery({ queryKey: ["/api/admin/coupons"], queryFn: () => jsonFetch("/api/admin/coupons") });
  const tickets = useQuery({ queryKey: ["/api/admin/support/tickets"], queryFn: () => jsonFetch("/api/admin/support/tickets") });
  const returns = useQuery({ queryKey: ["/api/admin/returns"], queryFn: () => jsonFetch("/api/admin/returns") });
  const abandoned = useQuery({ queryKey: ["/api/admin/abandoned-carts"], queryFn: () => jsonFetch("/api/admin/abandoned-carts") });
  const giftCards = useQuery({ queryKey: ["/api/admin/gift-cards"], queryFn: () => jsonFetch("/api/admin/gift-cards") });
  const shippingRules = useQuery({ queryKey: ["/api/admin/shipping-rules"], queryFn: () => jsonFetch("/api/admin/shipping-rules") });
  const carriers = useQuery({ queryKey: ["/api/admin/carriers"], queryFn: () => jsonFetch("/api/admin/carriers") });
  const audits = useQuery({ queryKey: ["/api/admin/audit-logs"], queryFn: () => jsonFetch("/api/admin/audit-logs") });

  const mutation = useMutation({ mutationFn: ({ url, method = "POST", body }: { url: string; method?: string; body?: unknown }) => jsonFetch(url, { method, headers: { "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined }), onSuccess: () => qc.invalidateQueries() });

  const statCards = useMemo(() => [
    ["Support tickets", tickets.data?.filter((x: any) => x.status !== "closed" && x.status !== "resolved").length || 0, Ticket],
    ["Returns", returns.data?.filter((x: any) => x.status === "requested").length || 0, RotateCcw],
    ["Active coupons", coupons.data?.filter((x: any) => x.active).length || 0, Tag],
    ["Abandoned carts", abandoned.data?.filter((x: any) => x.status === "active").length || 0, ShoppingBag],
  ], [tickets.data, returns.data, coupons.data, abandoned.data]);

  return <div className="space-y-6 p-4 md:p-6">
    <div>
      <h1 className="text-2xl font-bold">Commerce Features</h1>
      <p className="text-muted-foreground">Manage promotions, customer support, returns, delivery, retention and operational controls.</p>
    </div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
      {statCards.map(([label, value, Icon]: any) => <Card key={label}><CardContent className="p-4 flex items-center justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-bold">{value}</p></div><Icon className="h-6 w-6 text-muted-foreground" /></CardContent></Card>)}
    </div>

    <Tabs defaultValue="support" className="space-y-4">
      <TabsList className="flex flex-wrap h-auto gap-1">
        <TabsTrigger value="support">Support</TabsTrigger><TabsTrigger value="returns">Returns</TabsTrigger><TabsTrigger value="coupons">Coupons</TabsTrigger><TabsTrigger value="giftcards">Gift Cards</TabsTrigger><TabsTrigger value="delivery">Delivery</TabsTrigger><TabsTrigger value="abandoned">Abandoned Cart</TabsTrigger><TabsTrigger value="permissions">Permissions</TabsTrigger><TabsTrigger value="audit">Audit Log</TabsTrigger>
      </TabsList>

      <TabsContent value="support"><Card><CardHeader><CardTitle>Customer Support Tickets</CardTitle><CardDescription>Assign, reply and resolve customer issues.</CardDescription></CardHeader><CardContent className="space-y-3">{(tickets.data || []).map((t: any) => <div key={t.id} className="border rounded-lg p-4 space-y-2"><div className="flex justify-between gap-3"><div><b>{t.subject}</b><p className="text-sm text-muted-foreground">{t.customerName} · {t.customerEmail}</p></div><Badge>{t.status}</Badge></div><p className="text-sm">{t.message}</p><Textarea defaultValue={t.response || ""} placeholder="Admin response" onBlur={(e) => { if (e.target.value !== (t.response || "")) mutation.mutate({ url: `/api/admin/support/tickets/${t.id}`, method: "PATCH", body: { response: e.target.value, status: "in_progress" } }); }} /><div className="flex gap-2"><Select defaultValue={t.status} onValueChange={(status) => mutation.mutate({ url: `/api/admin/support/tickets/${t.id}`, method: "PATCH", body: { status } })}><SelectTrigger className="w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="open">Open</SelectItem><SelectItem value="in_progress">In progress</SelectItem><SelectItem value="resolved">Resolved</SelectItem><SelectItem value="closed">Closed</SelectItem></SelectContent></Select></div></div>)}{!(tickets.data || []).length && <p className="text-muted-foreground">No support tickets.</p>}</CardContent></Card></TabsContent>

      <TabsContent value="returns"><Card><CardHeader><CardTitle>Returns & Refunds</CardTitle><CardDescription>Review requests and record refund decisions.</CardDescription></CardHeader><CardContent className="space-y-3">{(returns.data || []).map((r: any) => <div key={r.id} className="border rounded-lg p-4"><div className="flex justify-between"><b>Order {r.orderId.slice(-8).toUpperCase()}</b><Badge>{r.status}</Badge></div><p className="text-sm mt-2">{r.reason}</p><p className="text-xs text-muted-foreground">{r.customerEmail}</p><div className="flex gap-2 mt-3"><Select defaultValue={r.status} onValueChange={(status) => mutation.mutate({ url: `/api/admin/returns/${r.id}`, method: "PATCH", body: { status } })}><SelectTrigger className="w-48"><SelectValue /></SelectTrigger><SelectContent>{["requested","approved","pickup_scheduled","received","refunded","rejected"].map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Input className="max-w-40" defaultValue={r.refundAmount || "0"} placeholder="Refund amount" onBlur={(e) => mutation.mutate({ url: `/api/admin/returns/${r.id}`, method: "PATCH", body: { refundAmount: e.target.value } })} /></div></div>)}{!(returns.data || []).length && <p className="text-muted-foreground">No return requests.</p>}</CardContent></Card></TabsContent>

      <TabsContent value="coupons"><Card><CardHeader><CardTitle>Advanced Coupons</CardTitle><CardDescription>Percentage/fixed discounts, minimum spend, usage limits and first-order restrictions.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid md:grid-cols-4 gap-3"><Input placeholder="Code" value={coupon.code} onChange={e => setCoupon({...coupon, code:e.target.value})}/><Select value={coupon.discountType} onValueChange={discountType => setCoupon({...coupon, discountType})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="percentage">Percentage</SelectItem><SelectItem value="fixed">Fixed amount</SelectItem></SelectContent></Select><Input placeholder="Discount value" value={coupon.discountValue} onChange={e => setCoupon({...coupon, discountValue:e.target.value})}/><Input placeholder="Minimum order" value={coupon.minimumOrderAmount} onChange={e => setCoupon({...coupon, minimumOrderAmount:e.target.value})}/><Input placeholder="Max discount" value={coupon.maximumDiscountAmount} onChange={e => setCoupon({...coupon, maximumDiscountAmount:e.target.value})}/><Input placeholder="Usage limit" value={coupon.usageLimit} onChange={e => setCoupon({...coupon, usageLimit:e.target.value})}/><Input placeholder="Per customer" value={coupon.perCustomerLimit} onChange={e => setCoupon({...coupon, perCustomerLimit:e.target.value})}/><Button onClick={() => mutation.mutate({url:"/api/admin/coupons", body:{...coupon, minimumOrderAmount:coupon.minimumOrderAmount || "0", maximumDiscountAmount:coupon.maximumDiscountAmount || undefined, usageLimit:coupon.usageLimit ? Number(coupon.usageLimit) : undefined, perCustomerLimit:Number(coupon.perCustomerLimit)}})}>Create Coupon</Button></div><Separator/>{(coupons.data || []).map((c:any)=><div key={c.id} className="border rounded p-3 flex items-center justify-between"><div><b>{c.code}</b><span className="ml-2 text-sm">{c.discountType === "percentage" ? `${c.discountValue}%` : `₹${c.discountValue}`}</span><p className="text-xs text-muted-foreground">Used {c.usageCount}/{c.usageLimit ?? "∞"}</p></div><Button variant="outline" onClick={() => mutation.mutate({url:`/api/admin/coupons/${c.id}`,method:"PATCH",body:{active:!c.active}})}>{c.active ? "Disable" : "Enable"}</Button></div>)}</CardContent></Card></TabsContent>

      <TabsContent value="giftcards"><Card><CardHeader><CardTitle>Gift Cards</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid md:grid-cols-4 gap-3"><Input placeholder="Code (optional)" value={gift.code} onChange={e=>setGift({...gift,code:e.target.value})}/><Input placeholder="Amount" value={gift.initialAmount} onChange={e=>setGift({...gift,initialAmount:e.target.value})}/><Input placeholder="Recipient email" value={gift.recipientEmail} onChange={e=>setGift({...gift,recipientEmail:e.target.value})}/><Button onClick={()=>mutation.mutate({url:"/api/admin/gift-cards",body:gift})}><Gift className="h-4 w-4 mr-2"/>Create Gift Card</Button></div>{(giftCards.data||[]).map((g:any)=><div key={g.id} className="border rounded p-3 flex justify-between"><div><b>{g.code}</b><p className="text-sm">₹{g.remainingAmount} / ₹{g.initialAmount}</p></div><Badge>{g.active?"Active":"Disabled"}</Badge></div>)}</CardContent></Card></TabsContent>

      <TabsContent value="delivery"><div className="grid lg:grid-cols-2 gap-4"><Card><CardHeader><CardTitle>Shipping Charges by Destination</CardTitle><CardDescription>India is the default market. Add state or country rules when charges differ.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="grid grid-cols-2 gap-2"><Input placeholder="Rule name" value={shippingRule.name} onChange={e=>setShippingRule({...shippingRule,name:e.target.value})}/><Input placeholder="Country (e.g. India)" value={shippingRule.country} onChange={e=>setShippingRule({...shippingRule,country:e.target.value})}/><Input placeholder="State (optional)" value={shippingRule.state} onChange={e=>setShippingRule({...shippingRule,state:e.target.value})}/><Input placeholder="Shipping charge" type="number" value={shippingRule.shippingCharge} onChange={e=>setShippingRule({...shippingRule,shippingCharge:e.target.value})}/><Input placeholder="Free shipping above (optional)" type="number" value={shippingRule.freeShippingThreshold} onChange={e=>setShippingRule({...shippingRule,freeShippingThreshold:e.target.value})}/><Input placeholder="Priority (lower wins)" type="number" value={shippingRule.priority} onChange={e=>setShippingRule({...shippingRule,priority:e.target.value})}/></div><Button onClick={()=>mutation.mutate({url:"/api/admin/shipping-rules",body:{...shippingRule,priority:Number(shippingRule.priority)}})}>Add Shipping Rule</Button><div className="max-h-72 overflow-auto space-y-2">{(shippingRules.data||[]).map((r:any)=><div key={r.id} className="flex justify-between border rounded p-2 text-sm"><span><b>{r.name}</b> · {r.state ? `${r.state}, ` : ""}{r.country || "All countries"} · ₹{r.shippingCharge}{r.freeShippingThreshold ? ` · Free above ₹${r.freeShippingThreshold}` : ""}</span><Button size="sm" variant="ghost" onClick={()=>mutation.mutate({url:`/api/admin/shipping-rules/${r.id}`,method:"DELETE"})}>Remove</Button></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle><Truck className="inline h-5 w-5 mr-2"/>Shipping Carriers</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Input placeholder="Carrier name" value={carrier.name} onChange={e=>setCarrier({...carrier,name:e.target.value})}/><Input placeholder="Tracking URL template" value={carrier.trackingUrlTemplate} onChange={e=>setCarrier({...carrier,trackingUrlTemplate:e.target.value})}/><Button onClick={()=>mutation.mutate({url:"/api/admin/carriers",body:carrier})}>Add</Button></div>{(carriers.data||[]).map((c:any)=><div key={c.id} className="border rounded p-2 text-sm">{c.name} · {c.trackingUrlTemplate || "Manual tracking"}</div>)}</CardContent></Card></div></TabsContent>

      <TabsContent value="abandoned"><Card><CardHeader><CardTitle>Abandoned Carts</CardTitle><CardDescription>Recover carts through your configured email/WhatsApp workflows.</CardDescription></CardHeader><CardContent className="space-y-2">{(abandoned.data||[]).map((a:any)=><div key={a.id} className="border rounded p-3 flex justify-between"><div><b>{a.customerEmail || "Guest"}</b><p className="text-sm">₹{a.cartTotal} · {Array.isArray(a.items) ? a.items.length : 0} items</p></div><Badge>{a.status}</Badge></div>)}</CardContent></Card></TabsContent>

      <TabsContent value="permissions"><Card><CardHeader><CardTitle><Shield className="inline h-5 w-5 mr-2"/>Admin Permissions</CardTitle><CardDescription>Store granular permissions for staff accounts without changing the existing admin login.</CardDescription></CardHeader><CardContent className="space-y-3"><Input placeholder="Admin user ID" value={permission.userId} onChange={e=>setPermission({...permission,userId:e.target.value})}/><Textarea value={permission.permissions} onChange={e=>setPermission({...permission,permissions:e.target.value})}/><Button onClick={()=>mutation.mutate({url:`/api/admin/permissions/${permission.userId}`,method:"PUT",body:{permissions:permission.permissions.split(",").map(x=>x.trim()).filter(Boolean)}})}>Save Permissions</Button></CardContent></Card></TabsContent>

      <TabsContent value="audit"><Card><CardHeader><CardTitle><ClipboardList className="inline h-5 w-5 mr-2"/>Admin Audit Log</CardTitle></CardHeader><CardContent className="space-y-2">{(audits.data||[]).map((a:any)=><div key={a.id} className="border-b py-2 text-sm"><b>{a.action}</b> · {a.entityType} · {a.entityId || ""}<span className="text-muted-foreground ml-2">{a.createdAt ? new Date(a.createdAt).toLocaleString() : ""}</span></div>)}</CardContent></Card></TabsContent>
    </Tabs>
  </div>;
}
